//! Build script for finetype CLI.
//!
//! When the `embed-models` feature is enabled, embeds the flat CharCNN model
//! (weights, labels, config) at compile time so the binary works standalone.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    // Models live at workspace root: ../../models/default -> char-cnn-v4/
    let models_base = PathBuf::from(&manifest_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("models");

    println!("cargo:rerun-if-changed={}", models_base.display());

    #[cfg(feature = "embed-models")]
    generate_embedded_models(&models_base);

    #[cfg(not(feature = "embed-models"))]
    let _ = models_base;
}

#[cfg(feature = "embed-models")]
fn generate_embedded_models(models_base: &std::path::Path) {
    // Follow the models/default symlink to find the active model
    let default_link = models_base.join("default");
    let flat_dir = if default_link.exists() {
        std::fs::read_link(&default_link)
            .map(|target| {
                if target.is_relative() {
                    models_base.join(target)
                } else {
                    target
                }
            })
            .unwrap_or_else(|_| models_base.join("char-cnn-v4"))
    } else {
        models_base.join("char-cnn-v4")
    };

    assert!(
        flat_dir.join("model.safetensors").exists(),
        "Flat model not found at {:?}. Run from workspace root or disable embed-models feature.",
        flat_dir
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = PathBuf::from(&out_dir).join("embedded_models.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n\n");

    let weights_path = flat_dir.join("model.safetensors").canonicalize().unwrap();
    let labels_path = flat_dir.join("labels.json").canonicalize().unwrap();
    let config_path = flat_dir.join("config.yaml").canonicalize().unwrap();

    code.push_str(&format!(
        "pub const FLAT_WEIGHTS: &[u8] = include_bytes!(\"{}\");\n",
        weights_path.display()
    ));
    code.push_str(&format!(
        "pub const FLAT_LABELS: &[u8] = include_bytes!(\"{}\");\n",
        labels_path.display()
    ));
    code.push_str(&format!(
        "pub const FLAT_CONFIG: &[u8] = include_bytes!(\"{}\");\n",
        config_path.display()
    ));

    fs::write(&dest, code).unwrap_or_else(|e| panic!("Failed to write {}: {}", dest.display(), e));
}
